import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit';
import { getCategories } from '../services/CategoryAPi';

export interface CategoryBidState {
  dataList: [],
  status: 'idle' | 'loading' | 'failed';
}

const initialState: CategoryBidState = {
  dataList: [],
  status: 'idle',
};

export const categoryBidState = createSlice({
    name: 'categoryBid',
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: { },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {
      builder
        .addCase(getCategories.pending, (state) => {
          state.status = 'loading';
        })
        .addCase(getCategories.fulfilled, (state, action) => {
          state.status = 'idle';
          state.dataList = action.payload
        })
        .addCase(getCategories.rejected, (state) => {
          state.status = 'failed';
        });
    },
  });
  
  const { reducer } = categoryBidState;
  export default reducer;
  

